package communicator2005;


import battlecode.common.*;

public class HQBehavior {
	
	/**
	 * 
	 * Defines the possible states the HQ can take in.
	 * 
	 */
	private enum HQState{
		INIT,DEFAULT;
	}
	
	
	/** locations that are generated by MapMaker are showing building positions**/
	public static MapLocation[] assemblyPositions;
	
	/** storage for the last target for the soldiers**/
	public static MapLocation lastTarget;
	
	public static MapLocation enemyHQ;
	public static MapLocation thisPos;
	
	/** The current state of the HQ. Allows to separate logical areas**/
	public static HQState state = HQState.INIT;
	
	/** contains the models the HQ has of the soldiers**/
	public static RobotRepresentation[] robots = new RobotRepresentation[StaticVariables.MAX_ROBOTS_SPAWN];
	
	/** containing all possible groups*/
	public static Group[] groups;
	
	/** debugging constant **/
	static int lifeCount = 0;
	/** debugging constant **/
	static int byteCodeSum = 0;

	static boolean buildSended = false;
	static boolean buildSended2 = false;
	/**
	 * Contains the logic of the HQ. is called every round.
	 * 
	 * @param rc
	 * @throws Exception
	 */
	public static void hqBehavior(RobotController rc) throws Exception{
		lifeCount ++;
		switch (state) {
		case INIT:
			enemyHQ = rc.senseEnemyHQLocation();
			thisPos = rc.getLocation();
			MapMaker.searchForSpots(rc, 0);
			assemblyPositions = new MapLocation[1];
			assemblyPositions[0] = MapMaker.bestFound;
			state = HQState.DEFAULT;
			groups = new Group[StaticVariables.MAX_POSSIBLE_GROUPS];
			for(int i = 0; i < groups.length; i ++){
				groups[i] = new Group(i);
			}
			break;
		case DEFAULT:
			tryToSpawn(rc);
            deliverID(rc);
            updateInteralRobotRepresentation(rc);
            
           	if(!buildSended){
           		System.out.println("assign");
           		groups[0].assignToOtherGroup(rc, groups[2], 0, 1);
           		if(groups[2].getSize() == 1){
               		groups[2].sendCommandToGroup(new MapLocation(rc.getMapWidth()/2,rc.getMapHeight()/2), StaticVariables.COMMAND_BUILD_PASTR, rc);
           			buildSended = true;
           		}
           	}
           	if(!buildSended2){
           		groups[0].assignToOtherGroup(rc, groups[3], 0, 1);
           		if(groups[3].getSize() == 1){
               		groups[3].sendCommandToGroup(new MapLocation(rc.getMapWidth()/2,rc.getMapHeight()/2).add(0, 1), StaticVariables.COMMAND_BUILD_NOISE_TOWER, rc);
           			buildSended2 = true;
           		}
           	}
           	groups[0].assignToOtherGroup(rc, groups[1], 0, 20);
//           	groups[1].sendCommandToGroup(assemblyPositions[0], StaticVariables.COMMAND_FARMING_MODE, rc);
           	
           	
           	
			break;
		}
	}
	public static void sendLineFormation(int groupID, RobotController rc, MapLocation p1, MapLocation p2, MapLocation middle) throws GameActionException{
		if(Clock.getRoundNum() < 20 ){
			System.out.println(p1 + " " + p2 + " " + middle);
		}
		
		int channel = StaticVariables.ROBOT_GROUP_COMMAND_CHANNEL_START+(groupID*StaticVariables.GROUP_CHANNEL_LENGTH_PER_GROUP);
		rc.broadcast(channel, StaticFunctions.locToInt(p1));
		rc.broadcast(channel+1, StaticFunctions.locToInt(p2));
		rc.broadcast(channel+2, StaticFunctions.locToInt(middle));
	}
	/**
	 * Reeds the feedback from all soldiers and updates the internal representation of the robots.
	 * This contains a counter that indicates if the soldier is alive, and also the map location
	 * of the soldiers.
	 * 
	 * @param rc
	 * @throws Exception
	 */
	public static void updateInteralRobotRepresentation(RobotController rc) throws Exception{

		for(int i=StaticVariables.MAX_ROBOTS_SPAWN; --i >= 0;) {
			if(robots[i] != null){
				
				//reeds the feedback associated with this soldier.
				int feedBack = rc.readBroadcast(StaticVariables.ROBOT_FEEDBACK_CHANNEL_START+i);
				
				//remembers the old life count of the soldier
				int current = robots[i].lifeTime;
				
				//sets the lifecount of the soldier to the new value. 
				robots[i].lifeTime = feedBack;
				
				//Interpreters the feedback to get the maplocation of the soldier.
//				robots[i].mL = new MapLocation((feedBack&16256)>>7,feedBack&127);

				//if the old lifecount is equal to the current, than the soldier died because he didn't send new feedback.
				//its a special case if the robot just spawned, in this case the previous feedback is equal to the current.
				//This continues until the soldier sends the first time some feedback.
				if(feedBack == current && !robots[i].initilazie){
					robots[i].notifyDeath();
					robots[i] = null;
					rc.broadcast(StaticVariables.ROBOT_FEEDBACK_CHANNEL_START+i,0);
					rc.broadcast(StaticVariables.ROBOT_COMMAND_CHANNEL_START+i, 0);
				}else if(feedBack != current){
					robots[i].initilazie = false;
				}
			}
		}
	}
	
	/**
	 * Reads the broadcast channel allocated for the robot id's.
	 * A 1 stands for a request for a new ID. The HQ looks for the next free space
	 * in the list of soldier-representations. The index of this channel +1 is the new 
	 * ID which is written back into the ID-channel. The Soldier reads this ID and clears
	 * the ID-channel(writing 0 into the ID-channel) for new requests.
	 * 
	 * @param rc
	 * @throws Exception
	 */
	public static void deliverID(RobotController rc) throws Exception{
		int current = rc.readBroadcast(StaticVariables.ROBOT_ID_CHANNEL);
		if(current == 1){
			for(int i = 0; i < robots.length; i ++){
				if(robots[i] == null){
					rc.broadcast(StaticVariables.ROBOT_ID_CHANNEL, (i+1)*10);
					robots[i] = new RobotRepresentation(i);
					groups[0].add(rc, robots[i]);
					return;
				}
			}
		}
	}

	public static void tryToSpawn(RobotController rc) throws Exception{
		if(rc.isActive()){
			int count = rc.senseRobotCount();
			if (count < StaticVariables.MAX_ROBOTS_SPAWN) {
				for(int i = 0; i < 8; i ++){
					if (rc.senseObjectAtLocation(HQBehavior.thisPos.add(StaticVariables.directions[i])) == null) {
						rc.spawn(StaticVariables.directions[i]);
						return;
					}
				}
				
			}
		}
	}
	
}
