package communicator;

import java.util.ArrayList;

import battlecode.common.*;

public class HQBehavior {
	
	/**
	 * 
	 * Defines the possible states the HQ can take in.
	 * 
	 */
	private enum HQState{
		INIT,DEFAULT;
	}
	
	/**
	 * 
	 * Represents what the HQ knows about a soldier.
	 * This representation needs maintains through constant updates.
	 * 
	 */
	private static class RobotRepresentation{
		int currentCommand;
		int iD;
		int lifeTime;
		boolean initilazie;
		MapLocation mL;
		public RobotRepresentation(int iD){
			this.initilazie = true;
			this.iD = iD;
			this.lifeTime = 0;
			this.currentCommand = StaticVariables.COMMAND_NOT_RECEIVED_YET;
		}
	}
	
	/** locations that are generated by MapMaker are showing building positions**/
	public static MapLocation[] assemblyPositions;
	
	/** storage for the last target for the soldiers**/
	public static MapLocation lastTarget;
	
	public static MapLocation enemyHQ;
	
	/** The current state of the HQ. Allows to separate logical areas**/
	public static HQState state = HQState.INIT;
	
	/** contains the models the HQ has of the soldiers**/
	public static RobotRepresentation[] robots = new RobotRepresentation[StaticVariables.MAX_ROBOTS_SPAWN];
	
	
	public static ArrayList<RobotRepresentation> attacking = new ArrayList<RobotRepresentation>();
	public static ArrayList<RobotRepresentation> assembling= new ArrayList<RobotRepresentation>();
	public static ArrayList<RobotRepresentation> building= new ArrayList<RobotRepresentation>();
	public static ArrayList<RobotRepresentation> free= new ArrayList<RobotRepresentation>();
	
	
	/** debugging constant **/
	static int lifeCount = 0;
	/** debugging constant **/
	static int byteCodeSum = 0;
	
	/**
	 * Contains the logic of the HQ. is called every round.
	 * 
	 * @param rc
	 * @throws Exception
	 */
	public static void hqBehavior(RobotController rc) throws Exception{
		int prevByteCode = Clock.getBytecodeNum();
		lifeCount ++;
		switch (state) {
		case INIT:
			// builds internal map which is currently unused
			MapMaker.makeMap(rc);
			assemblyPositions = MapMaker.buildImportanceMap(2,rc);
			state = HQState.DEFAULT;
			enemyHQ = rc.senseEnemyHQLocation();
			break;
		case DEFAULT:
//			System.out.println(lifeCount + " try to spawn: " + rc.senseRobotCount());
			tryToSpawn(rc);
			deliverID(rc);
			updateInteralRobotRepresentation(rc);
			MapLocation[] enemyPastr = rc.sensePastrLocations(rc.getTeam().opponent());
			
			// the command structure is currently working as a Flip-flop this means that an attacking command is send as 
			// a attack command, then as a assembling command than as an attacking command, then as an assembling command
			// and so on.
			// this is related to the Arraylists which store the current representation and the commands they are currently processing.
			// this is just at the beginning to test how the byte code is reduced by not sending redundantly commands.
			// this will change to a new command structure and should be incorporated into the internal states.
			if(enemyPastr.length > 0){
				deliverCommand(enemyPastr[0], rc, StaticVariables.COMMAND_ATTACK_LOCATION);			
				if(lastTarget != null && enemyPastr[0].x != lastTarget.x && enemyPastr[0].y != lastTarget.y ){
					deliverCommand(enemyPastr[0], rc, StaticVariables.COMMAND_ASSEMBLE_AT_LOCATION);
				}
				lastTarget = enemyPastr[0];
			}else{
				//send to all robots an assemble command. The position is retrieved from the MapMaker.
				deliverCommand(assemblyPositions[0], rc, StaticVariables.COMMAND_ASSEMBLE_AT_LOCATION);
			}
			// after a while send a build-pasture-command to the last spawned soldier.
			if(lifeCount >= 400 &&rc.sensePastrLocations(rc.getTeam()).length == 0){
				for(int i = robots.length-1; i >= 0; i --){
					if(robots[i] != null){
						sendCommand(assemblyPositions[0], StaticVariables.ROBOT_COMMAND_CHANNEL_START+i, rc, StaticVariables.COMMAND_BUILD_PASTR);
						return;
					}
				}
			}
			//send scout soldier
			for(int i = 0; i < robots.length; i ++){
				if(robots[i] != null){
					sendCommand(enemyHQ, StaticVariables.ROBOT_COMMAND_CHANNEL_START+i, rc, StaticVariables.COMMAND_SCOUT_LOCATION);
					System.out.println("sends scout command to " + i);
					return;
				}
			}
			break;
		}
		byteCodeSum +=  Clock.getBytecodeNum()-prevByteCode;
//		System.out.println(byteCodeSum/Clock.getRoundNum());
	}
	
	/**
	 * Reeds the feedback from all soldiers and updates the internal representation of the robots.
	 * This contains a counter that indicates if the soldier is alive, and also the map location
	 * of the soldiers.
	 * 
	 * @param rc
	 * @throws Exception
	 */
	public static void updateInteralRobotRepresentation(RobotController rc) throws Exception{

		for(int i=StaticVariables.MAX_ROBOTS_SPAWN; --i >= 0;) {
			if(robots[i] != null){
				
				//reeds the feedback associated with this soldier.
				int feedBack = rc.readBroadcast(StaticVariables.ROBOT_FEEDBACK_CHANNEL_START+i);
				
				//remembers the old life count of the soldier
				int current = robots[i].lifeTime;
				
				//sets the lifecount of the soldier to the new value. 
				robots[i].lifeTime = feedBack;
				
				//Interpreters the feedback to get the maplocation of the soldier.
				robots[i].mL = new MapLocation(feedBack/1000,(feedBack/10)%100);
				
				//if the old lifecount is equal to the current, than the soldier died because he didn't send new feedback.
				//its a special case if the robot just spawned, in this case the previous feedback is equal to the current.
				//This continues until the soldier sends the first time some feedback.
				if(feedBack == current && !robots[i].initilazie){
					robots[i] = null;
					rc.broadcast(StaticVariables.ROBOT_FEEDBACK_CHANNEL_START+i,0);
				}else if(feedBack != current){
					robots[i].initilazie = false;
				}
			}
		}
	}
	
	/**
	 * Soldiers are grouped by the task they currently have.
	 * To deliver a new task the robots are moved from any list to the target list
	 * that represents a certain command. 
	 * 
	 * @param loc of the attack, or assemble move
	 * @param rc
	 * @param command
	 * @throws Exception
	 */
	public static void deliverCommand(MapLocation loc, RobotController rc, int command) throws Exception{
		switch(command){
		case StaticVariables.COMMAND_ASSEMBLE_AT_LOCATION:
			deliverCommandToGroup(loc,HQBehavior.attacking,HQBehavior.assembling,command,rc);
			deliverCommandToGroup(loc,HQBehavior.free,HQBehavior.assembling,command,rc);
			break;
		case StaticVariables.COMMAND_ATTACK_LOCATION:
			deliverCommandToGroup(loc,HQBehavior.assembling,HQBehavior.attacking,command,rc);
			deliverCommandToGroup(loc,HQBehavior.free,HQBehavior.attacking,command,rc);
			break;
		case StaticVariables.COMMAND_BUILD_PASTR:
			break;
		}
	}

	/**
	 * Moves all soldiers from one list to the other and sends a command to the moved
	 * soldiers.
	 * 
	 * @param loc is the target maplocation delivered to the soldiers.
	 * @param from is the arraylist containing the soldiers with the old command.
	 * @param to is the arraylist the soldiers are transfered to.
	 * @param command to be send.
	 * @param rc
	 * @throws Exception
	 */
	public static void deliverCommandToGroup(MapLocation loc, ArrayList<RobotRepresentation> from, ArrayList<RobotRepresentation> to, int command, RobotController rc) throws Exception{
		while(from.size() != 0){
			RobotRepresentation rR = from.get(0);
			sendCommand(loc, StaticVariables.ROBOT_COMMAND_CHANNEL_START+rR.iD, rc, StaticVariables.COMMAND_ASSEMBLE_AT_LOCATION);
			to.add(rR);
			from.remove(0);
		}
	}
	
	/**
	 * Reads the broadcast channel allocated for the robot id's.
	 * A 1 stands for a request for a new ID. The HQ looks for the next free space
	 * in the list of soldier-representations. The index of this channel +1 is the new 
	 * ID which is written back into the ID-channel. The Soldier reads this ID and clears
	 * the ID-channel(writing 0 into the ID-channel) for new requests.
	 * 
	 * @param rc
	 * @throws Exception
	 */
	public static void deliverID(RobotController rc) throws Exception{
		int current = rc.readBroadcast(StaticVariables.ROBOT_ID_CHANNEL);
		if(current == 1){
			for(int i = 0; i < robots.length; i ++){
				if(robots[i] == null){
					rc.broadcast(StaticVariables.ROBOT_ID_CHANNEL, (i+1)*10);
					robots[i] = new RobotRepresentation(i);
					free.add(robots[i]);
					return;
				}
			}
		}
	}

	public static void tryToSpawn(RobotController rc) throws Exception{
		if(rc.isActive()){
			int count = rc.senseRobotCount();
			if (count <= StaticVariables.MAX_ROBOTS_SPAWN) {
				Direction toEnemy = rc.getLocation().directionTo(
						rc.senseEnemyHQLocation());
				if (rc.senseObjectAtLocation(rc.getLocation().add(toEnemy)) == null) {
					rc.spawn(toEnemy);
				}
			}
		}
	}
	
	/**
	 * Sends a specific command to a certain channel. Incorporates a maplocation into the command.
	 * 
	 * @param loc is the target maplocation delivered to the soldiers. 
	 * @param channelID is the index of the channel in which the command is delivered.
	 * @param rc
	 * @param command
	 * @throws Exception
	 */
	public static void sendCommand(MapLocation loc, int channelID, RobotController rc, int command) throws Exception{
		int broadcast = StaticFunctions.locToInt(loc) + (10000 * command);
		rc.broadcast(channelID, broadcast);
	}
	
}
